global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'patisoru'
    metrics_path: '/actuator/prometheus' # the location where prometheus metrics are exposed
    scrape_interval: 5s
    static_configs:
      - targets: ['patisoru:8080']  # Use the service name 'patisoru'